#Config for ChatItem
#For info visit
#https://www.spigotmc.org/resources/chatitem.19064/

#Version info, DON'T TOUCH
config-version: 12

#General configuration
General:
  #The placeholders you want to use for the item. You can add as many as you want.
  placeholders:
    - "[i]"
    - "{item}"
  #  How will the item be displayed in chat? {name} represents the display name of
  # the item, or material name (ex. Diamond Sword) if it doesn't have a customized
  # display name nor any available translation, and {amount} will be replaced by
  # the amount-format configured bellow.
  #  You can use color codes.
  name-format: "&f<&b&l&o{name} {amount}&f>&r"
  #  The amount format that will replace the {amount} placeholder in the 'name-format'
  # field above. The {times} placeholder represents the number of times the item is
  # presented in the itemstack, in other words, the actual item amount in the stack
  # the player holds. You can use color codes too.
  amount-format: "x{times}"
  #  Should we apply the colors/formats set in the name format and/or amount format
  # settings on the name of the item even though it already has a color of it's own,
  # like a custom display name? Setting this to true will always disregard any color
  # or or message
  color-if-already-colored: true
  #  Should we add the item amount even if there's only one item in the stack?
  force-add-amount: true
  #  Should we let the message through, as-is (with the placeholder not replaced)
  # if the user doesn't have permission or if the user is on cooldown?
  let-message-through: true
  #  Should we cancel the user message if the item in his (main) hand is air or null?
  # (No item in hand, that is)
  deny-if-no-item: false
  #  If the above (deny-if-no-item) is set to false, what should the placeholder be replaced with?
  # Bellow you can configure that behaviour.
  hand:
    #  Should the empty hand formatting be totally disabled? That will just leave the placeholder
    # untouched in the final message
    disabled: false
    #  The string the placeholder shall be replaced with. You can use {name} as a placeholder for
    # the player's name and {display-name} as a placeholder for the player's display (custom) name.
    name: "&f<&b&l&o{display-name}&b&l&o's hand&f>"
    #  The text to be displayed whe users hove their cursor above the name
    tooltip:
      - "&7Nothing to see here"
      - "&7Just the empty hand of {display-name}."

  #  Here you can choose which commands will the plugin attempt to parse. Console commands will all be ignored,
  # however player commands will be taken into consideration. To add a command, simply add an element to the list
  # bellow containing an alias (or name) for that command.
  #  It is enough to add only ONE alias for each command, and the others will automatically be supported. However,
  # this is only available for plugin commands. If you're planning to add bukkit or mojang commands here, you'll have
  # to manually specify ALL aliases for those.
  commands:
    - "msg"
  #  Here you can set when the players should see the no-permission message (defined in the 'Messages' section bellow).
  # 'normal' dictates whether the user should see the message when using the placeholder in normal chat, and 'command'
  # sets whether the user should see it when using the placeholder in a command.
  show-no-permission-message:
    normal: true
    command: false
  #  Here you can set the limit on how many placeholders a user is allowed to use inside a message.
  # Allowing too many placeholders can result in client crashes.
  limit: 8
  #  The cooldown, in seconds, between allowing players to send messages with items. Setting this to 0
  # will remove the cooldown entirely.
  cooldown: 60


#  Messages section. You can disable any of them by simply leaving them empty, like this: ""
Messages:
  #  The message users will get upon attempting to use the placeholder without any item in hand.
  # Only works if 'General.deny-if-no-item' is set to true!
  deny-message: "&c&lYou have no item in hand!"
  #  The message you will get after reloading the plugin using /cireload.
  reload-success: "&b&lSuccessful reload!"
  #  The message a player will get when attempting to send a message with more placeholders then the allowed limit.
  limit-message: "&c&lYou can only add 8 item placeholders per message!"
  #  The message to display players when they can't display items in chat due to the cooldown
  cooldown-message: "&c&lYou can only use items in chat once a minute! You have {remaining} left!"
  #  The no permission message to be showed to players who don't have the required permission to use the placeholder
  no-permission: "&c&lI'm sorry, but you are not allowed to use the placeholder in chat!"
  #  All the fields bellow shold be translated in your own language. Those will be used in the {remaining} format of the cooldown message.
  # You should leave a space as a PREFIX as we will add a number in front of them
  seconds: " seconds"
  minutes: " minutes"
  hours: " hours"
